baseURL = "https://apelsinchikov.github.io/sdd-system-analyst/"
languageCode = "ru"
title = "SDD System Analyst"
theme = "techdoc"

defaultContentLanguage = "ru"
hasCJKLanguage = true

[params]
  description = "Spec-Driven Development для системного аналитика"
  github_repository = "https://github.com/apelsinchikov/sdd-system-analyst"
  github_doc_repository = "https://github.com/apelsinchikov/sdd-system-analyst"
  menu_style = "slide-menu"
  ordersectionsby = "weight"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6
    ordered = false
