title: SDD System Analyst
baseURL: https://apelsinchikov.github.io/sdd-system-analyst/
theme: book

[params]
  # Book configuration
  BookToC = true
  BookTheme = "auto"
  BookRepo = "https://github.com/apelsinchikov/sdd-system-analyst"
  BookEditPath = "edit/main/content"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
