baseURL = "https://apelsinchikov.github.io/sdd-system-analyst/"
languageCode = "ru"
title = "SDD System Analyst"

[params]
  description = "Spec-Driven Development для системного аналитика"
  author = "apelsinchikov"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML"]
